Inclusao de css
LilianePaixao/novos-titas pull request #17
Opened 2021-12-28 15:14 UTC by LilianePaixao

2021-12-30 11:58 UTC, edmargomes requested changes

2021-12-30 11:58 UTC, edmargomes commented on exercicio2/index.php
> +    <link rel="stylesheet" href="style.css"
Necessário fechar a tag de link `/>`

2021-12-30 11:58 UTC, edmargomes commented on exercicio2/index.php
> +        <input type ="number"  name = "number" id="numerodigitado"class= "input-padrao" required placeholder= "O número pode ser inteiro, real...">
em html, os atributos de um tag são feitos colocando o = junto com a propriedade e espaço depois da aspas
veja esse input que vc fez corretamente:

`<input type="submit" value="Enviar">`

2021-12-30 11:58 UTC, edmargomes commented on exercicio2/style.css
> +    }
Fechar sempre as chaves no mesmo alinhamento da do objeto. igual você fez em .input-padrao

2021-12-30 15:17 UTC, LilianePaixao commented on exercicio2/index.php
> +    <link rel="stylesheet" href="style.css"
faltou mesmo...mas acho que é somente >
ex: <link rel="stylesheet" href="chrome://resources/css/text_defaults_md.css">

2021-12-30 15:18 UTC, LilianePaixao commented on exercicio2/index.php
> +        <input type ="number"  name = "number" id="numerodigitado"class= "input-padrao" required placeholder= "O número pode ser inteiro, real...">
corrigido

2021-12-30 15:18 UTC, LilianePaixao commented on exercicio2/style.css
> +    }
feito

2021-12-31 15:16 UTC, edmargomes requested changes

2021-12-31 15:16 UTC, edmargomes commented on exercicio2/index.php
> +    <html lang="pt-br">
tag html é na linha 1, não dentro do head

2022-01-02 16:23 UTC, LilianePaixao commented on exercicio2/index.php
> +    <html lang="pt-br">
ah, entendi

2022-01-02 16:57 UTC, LilianePaixao commented on exercicio2/index.php
> +    <html lang="pt-br">
feito
coloquei assim
<!DOCTYPE html>
    <html lang="pt-br">
    <head>  
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/exercicio3/style.css">    
    </head>
    
    A odentação é essa?

2022-01-02 17:25 UTC, edmargomes approved these changes

2022-01-02 17:25 UTC, edmargomes commented on exercicio2/index.php
> +    <html lang="pt-br">
Perfeito

2022-01-02 17:25 UTC, merged