Inclusao de css e correçao de php
LilianePaixao/novos-titas pull request #19
Opened 2021-12-31 22:56 UTC by LilianePaixao

Não consigo entender o porquê de quando é mulher e que tem 25, 26 anos dá aceita também...

2022-01-02 18:48 UTC, edmargomes requested changes

2022-01-02 18:48 UTC, edmargomes commented on exercicio3/index.php
> +                if($_POST["name"] == null and $_POST["sexo"]== null and $_POST["idade"]== null){
Vc usou `and` ao invés de `&&` nos ifs

2022-01-02 18:56 UTC, LilianePaixao commented on exercicio3/index.php
> +                if($_POST["name"] == null and $_POST["sexo"]== null and $_POST["idade"]== null){
é a mesma semântica, testei um e outro porque não entendi porque continua dando erro

2022-01-03 02:17 UTC, merged

2022-01-03 18:38 UTC, LilianePaixao commented
Uai você já fez o merge? então como vou te mostrar que corrigi a demanda solicitada lá no board?