Exercicio 10 com css
LilianePaixao/novos-titas pull request #29
Opened 2022-01-27 13:43 UTC by LilianePaixao

2022-01-28 20:15 UTC, edmargomes requested changes

2022-01-28 20:15 UTC, edmargomes commented on exercicio10/index.php
> +                ($numero <= 0) ? $neg[] = $numero : $pos[] = $numero;
numero 0 não é negativo, se digito 0 ele será contato nos negativos

2022-01-28 20:15 UTC, edmargomes commented on exercicio10/index.php
> +        $array_numeros = explode (",", $numerosInformados);
Ajustar identação

2022-01-28 20:15 UTC, edmargomes commented on exercicio10/index.php
> +        $numerosInformados = $_POST["numero"];
Ajustar a identação

2022-01-29 14:09 UTC, LilianePaixao commented on exercicio10/index.php
> +        $numerosInformados = $_POST["numero"];
sendo honesta, não sei direito como identar

2022-01-29 22:16 UTC, edmargomes requested changes

2022-01-29 22:16 UTC, edmargomes commented on exercicio10/index.php
> +                    echo "A quantidade de números negativos é " . count($neg). "</br>" ;
Array numeros, for e echo deveriam estar alinhados com a variavel numerosInformados

2022-02-01 22:17 UTC, merged