Teste do exercicio2
LilianePaixao/novos-titas pull request #34
Opened 2022-02-05 15:21 UTC by LilianePaixao

2022-02-05 15:24 UTC, LilianePaixao commented
É necessário acessar localhost:8585 para realizar o teste

2022-02-09 03:03 UTC, edmargomes requested changes

2022-02-09 03:03 UTC, edmargomes commented on tests/acceptance/Exercicio2Cest.php
> +    public function exercici1Works(AcceptanceTester $I)
Vc chamou a função de exercici1

2022-02-09 03:03 UTC, edmargomes commented on tests/acceptance/Exercicio2Cest.php
> +    public function CheckIndex(AcceptanceTester $I)
Creio q não precisa testar o index de novo, esse teste ja é feito no arquivo do test 1

2022-02-09 03:03 UTC, edmargomes commented on tests/acceptance/Exercicio2Cest.php
> +        $I->see('39 não é divisível por 10, por 5, nem por 2');
Excelente cobertura de testes, todos os cenarios pelo q percebi, parabens!!!!

2022-02-10 02:30 UTC, edmargomes approved these changes

2022-02-10 02:30 UTC, merged