Nvt 107
LilianePaixao/novos-titas pull request #48
Opened 2022-03-08 19:10 UTC by LilianePaixao

Solicitações atendidas sobre:
-inclusão do url 
-exportação da estrutura do banco de dados

2022-03-09 12:38 UTC, edmargomes approved these changes

2022-03-09 12:49 UTC, edmargomes requested changes

2022-03-09 12:49 UTC, edmargomes commented on README.md
> +[dockerhub](https://hub.docker.com/r/phpmyadmin/phpmyadmin/)
Colocar isso onde? Ja não esta feito no seu arquivo docker-compose? Se la ja está inserido não é necessario eu fazer o set em algum lugar e essa parte pode ser removido

2022-03-09 12:49 UTC, edmargomes commented on README.md
> +- Fill in the Field username: titas
Onde é para inserir isso?

2022-03-09 12:49 UTC, edmargomes commented on README.md
> +- choice the format SQL and execute
Preciso exportar algo para o sistema funcionar?

2022-03-09 12:51 UTC, edmargomes requested changes

2022-03-09 12:51 UTC, edmargomes commented on exercicio-banco-dados/docker-compose.yml
> +      - 8080:8080
Não precisa do adminer, se tiver removido em outro branch deixa aqui como está, se não remove ele. Se vc usa somente o phpmyadmin não tem necessidade desse

2022-03-09 17:09 UTC, LilianePaixao commented on README.md
> +[dockerhub](https://hub.docker.com/r/phpmyadmin/phpmyadmin/)
ok irei remover, pois isso já está no docker-compose.yml

2022-03-09 17:11 UTC, LilianePaixao commented on exercicio-banco-dados/docker-compose.yml
> +      - 8080:8080
ok
retirado.

2022-03-09 17:13 UTC, LilianePaixao commented on README.md
> +- choice the format SQL and execute
Não.
Eu preciso explicar que é necessário importar o arquivo de sql?

2022-03-11 12:46 UTC, edmargomes approved these changes

2022-03-11 12:46 UTC, merged