Nvt 116
LilianePaixao/novos-titas pull request #52
Opened 2022-03-14 19:07 UTC by LilianePaixao

Para esse exercício foram solicitados 3 campos
1º campo: o usuário informa a massa do elemento radioativo
2º campo: o usuário informa a porcentagem de perda para essse elemento radioativo
3º campo: um campo para dizer em quanto tempo perde essa % em segundos.

O terceiro campo eu não entendi, pois esse é o que a lógica do programa calculará para nós.

Favor avaliar

2022-03-16 14:03 UTC, edmargomes requested changes

2022-03-16 14:03 UTC, edmargomes commented on exercicio15/index.php
> +
Faltou o campo em segundos para ocorrer a perda. Nessa implementação de codigo trata que sempre irá gastar 1 minuto para ocorrer a perda, porem quem tem q digitar isso é o usuario, ele pode dizer q se perde 20% a cada 10 segundos e não a cada minuto

2022-03-16 14:03 UTC, edmargomes commented on exercicio15/index.php
> +                $tempo++;
Precisa pegar o segundos que o usuario definiu para cada rodada de perda e ir somando e não considerar sempre 1 minuto para a perda

2022-03-17 15:46 UTC, LilianePaixao commented on tests/acceptance/Exercicio15Cest.php
> +        $I->see('Serão necessários 3 minutos, ' );
Ainda não consegui pensar em como fazer isso :/

2022-03-19 16:35 UTC, edmargomes approved these changes

2022-03-19 16:35 UTC, merged