Nvt 120
LilianePaixao/novos-titas pull request #58
Opened 2022-03-22 21:17 UTC by LilianePaixao

Exercício 16
conexão com banco de dados

2022-03-29 18:33 UTC, edmargomes requested changes

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +
Corrigir identação

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +               var_dump($numeroParJuntos);
Corrigir identação

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +
Corrigir identação, remover excesso de quebras de linha

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +
Bastava 1 quebra de linha, aqui tem 2

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +        //  $numeroImparJuntos = mysqli_escape_string($connect, $sql);
Codigo comentado

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +             //   header('Location:index.php?erro');
Codigo comentado, creio q deveria remover

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +
Exceço de quebra de linhas

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +                            ?>
Corrigir identação

2022-03-29 18:33 UTC, edmargomes commented on exercicio16/index.php
> +
Excesso de quebra de linhas

2022-03-29 18:33 UTC, edmargomes commented on tests/acceptance/Exercicio16Cest.php
> +        $I->see('Os números pares são Array ( [0] => 2 [1] => 4 [2] => 6 ' );
Falta os testes de banco de dados, vou mostrar na próxima aula

2022-03-29 19:35 UTC, LilianePaixao commented on exercicio16/index.php
> +
Removi o excesso de linhas, só fico na dúvida da identação...pra mim tá dentro do if ...

2022-03-29 19:36 UTC, LilianePaixao commented on exercicio16/index.php
> +        //  $numeroImparJuntos = mysqli_escape_string($connect, $sql);
retirado

2022-03-29 19:42 UTC, LilianePaixao commented on tests/acceptance/Exercicio16Cest.php
> +        $I->see('Os números pares são Array ( [0] => 2 [1] => 4 [2] => 6 ' );
Vou tentar fazer e te mostro na próxima aula

2022-04-01 17:01 UTC, edmargomes approved these changes

2022-04-01 17:01 UTC, merged