Nvt 124
LilianePaixao/novos-titas pull request #62
Opened 2022-03-29 01:23 UTC by LilianePaixao

2022-03-29 18:50 UTC, edmargomes requested changes

2022-03-29 18:50 UTC, edmargomes commented on exercicio17/index.php
> +                echo "A porcentagem de números pares é ". $par * 5 . " %";
Corrigir identação, todo esse codigo ta dentro do if

2022-03-29 18:50 UTC, edmargomes commented on exercicio17/index.php
> +                echo "A média será". array_sum($array_numeros);
Calculo de media errada

2022-03-29 18:50 UTC, edmargomes commented on exercicio17/index.php
> +                echo "A média será". array_sum($array_numeros);
A linha 35 e 37 eram oportunidades para treinar  if dentro do for para pegar o maior e menor numero.

A soma do array poderia usar $sum += $numero que iria utilizar aquilo q vc disse q entendeu, mas não usa.

Não precisa refazer se não quiser.

2022-03-29 18:50 UTC, edmargomes commented on tests/acceptance/Exercicio17Cest.php
> +        $I->see('O maior número é 20A média será210 ' );
Faltou o menor numero e calculo de media esta errado neh

2022-03-29 19:25 UTC, LilianePaixao commented on exercicio17/index.php
> +                echo "A média será". array_sum($array_numeros);
A linha 35 e 37 eram oportunidades para treinar if dentro do for para pegar o maior e menor numero.
(Não entendi)

2022-04-01 17:03 UTC, edmargomes approved these changes

2022-04-01 17:03 UTC, merged