Nvt 125
LilianePaixao/novos-titas pull request #65
Opened 2022-03-30 16:29 UTC by LilianePaixao

BD connection.

2022-04-04 18:34 UTC, edmargomes requested changes

2022-04-04 18:34 UTC, edmargomes commented on tests/acceptance/Exercicio17Cest.php
> +        $I->see('Os números informados devem ser positivos.' );
Faltou testes de banco de dados

2022-04-04 18:35 UTC, edmargomes requested changes

2022-04-04 18:35 UTC, edmargomes commented on exercicio17/index.php
> +
Quando é que vc salva no banco de dados

2022-04-06 18:13 UTC, LilianePaixao commented on tests/acceptance/Exercicio17Cest.php
> +        $I->see('Os números informados devem ser positivos.' );
Coloquei assim:
//BD query
        $I->seeInDatabase('Numeros', ['name' => 'Davert', 'email' => 'davert@mail.com']);
    }

2022-04-13 03:06 UTC, edmargomes approved these changes

2022-04-13 03:06 UTC, merged