Exercicio14teste
LilianePaixao/novos-titas pull request #75
Opened 2022-04-13 01:35 UTC by LilianePaixao

Correção de teste do exercicio14.

2022-04-15 18:57 UTC, edmargomes requested changes

2022-04-15 18:57 UTC, edmargomes commented on tests/acceptance/Exercicio14Cest.php
>      }
Após o teste de database não precisa testar nenhuma msg que apareça na tela de sucesso? Veja que os outros see vc checa uma msg de status.

2022-04-16 00:46 UTC, LilianePaixao commented on tests/acceptance/Exercicio14Cest.php
>      }
Incluído 
$I->see('Serão necessários 31 anos, para que o segundo estudante seja maior que o primeiro estudante informado.' );

2022-04-16 14:08 UTC, edmargomes approved these changes

2022-04-16 14:08 UTC, merged