Nvt 133
LilianePaixao/novos-titas pull request #76
Opened 2022-04-13 17:48 UTC by LilianePaixao

2022-04-15 12:10 UTC, edmargomes requested changes

2022-04-15 12:10 UTC, edmargomes commented on base/includes/footer.php
> +
Remover excesso de quebra de linha desnecessaria

2022-04-15 12:10 UTC, edmargomes commented on tests/acceptance/Exercicio18Cest.php
> +    }
Falta teste para checar a listagem, aqui testa formulario, se os dados foram para o banco, mas não testa se a listagem existe

2022-04-15 12:10 UTC, edmargomes commented on tests/acceptance/Exercicio18Cest.php
> +        $I->fillField('numbers2', '-1,-2,-3,-5,-7,-9,10,11,15,16');
Ideal que o teste repita pelo menos numeros comuns entre os dois vetores

2022-04-15 12:10 UTC, edmargomes commented on tests/acceptance/Exercicio18Cest.php
> +        $I->seeInDatabase('exercicio18', ['numbers1' => '1,2,3,4,5,6,7,8,9,0', 'numbers2'=>'-1,-2,-3,-5,-7,-9,10,11,15,16', 'result' => '1,2,3,4,5,6,7,8,9,0']);
Errado, ele tem q exibir os valores do vetor 1 e do vetor 2 q não são comuns, seu algoritmo somente considera o vetor 1

2022-04-16 11:00 UTC, LilianePaixao commented on tests/acceptance/Exercicio18Cest.php
> +        $I->fillField('numbers2', '-1,-2,-3,-5,-7,-9,10,11,15,16');
não pode ser os números incomuns?

2022-04-16 11:01 UTC, LilianePaixao commented on tests/acceptance/Exercicio18Cest.php
> +        $I->seeInDatabase('exercicio18', ['numbers1' => '1,2,3,4,5,6,7,8,9,0', 'numbers2'=>'-1,-2,-3,-5,-7,-9,10,11,15,16', 'result' => '1,2,3,4,5,6,7,8,9,0']);
isso números incomuns

2022-04-28 16:32 UTC, edmargomes approved these changes

2022-04-28 16:33 UTC, merged